name: release_inai_cocoapod

on:
  push:
    tags:
      - '*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0 
        
      - name: Clone SDK Repo
        run: |
          git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/inaitech/inai-ios-sdk.git sdkclone
      - name: Run build Script
        working-directory: ./sdkclone
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
        
      - name: Commit Framework File and update tag
        working-directory: ./
        run: |
          rm -rf ./inai_ios_sdk.xcframework
          mv ./sdkclone/inai_ios_sdk.xcframework ./inai_ios_sdk.xcframework
          git config --global user.email "support@inai.io"
          git config --global user.name "${{ secrets.GH_USERNAME }}"

          git add inai_ios_sdk.xcframework
          git commit -m "Updating framework file to latest"
          git tag $(git describe --tags `git rev-list --tags --max-count=1`) -f
        shell: bash
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          tags: true
  
      # Install Cocoapods on the machine
      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export POD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
