name: release_inai_cocoapod

on:
  push:
    tags:
      - 'v*.*.*'
      
  workflow_dispatch:
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false 
          fetch-depth: 0 
        
      - name: Clone SDK Repo
        run: |
          git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/inaitech/inai-ios-sdk.git sdkclone
        shell: bash
      
      - name: Configure secrets
        env:
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          SENTRY_ENVIRONMENT: ${{ secrets.SENTRY_ENVIRONMENT }}
          SENTRY_SECRET: ${{ secrets.SENTRY_SECRET }}
          SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
        run: |
          sed -i '' "s/let SENTRY_URL.*$/let SENTRY_URL = \"\$SENTRY_URL\"/g" ./inai-ios-sdk/Crashlytics/UploadCrashEvent.swift
          
          sed -i '' "s/let SENTRY_SECRET.*$/let SENTRY_SECRET = \"\$SENTRY_SECRET\"/g" ./inai-ios-sdk/Crashlytics/UploadCrashEvent.swift
          
          sed -i '' "s/let SENTRY_KEY.*$/let SENTRY_KEY = \"\$SENTRY_KEY\"/g" ./inai-ios-sdk/Crashlytics/UploadCrashEvent.swift
          
          sed -i '' "s/let SENTRY_ENVIRONMENT.*$/let SENTRY_ENVIRONMENT = \"\$SENTRY_ENVIRONMENT\"/g" ./inai-ios-sdk/Crashlytics/UploadCrashEvent.swift
          
          sed -i '' "s/static let SENTRY_URL.*$/static let SENTRY_URL = \"\$SENTRY_URL\"/g" ./inai-ios-sdk/Crashlytics/CrashEye.swift
                    
      - name: Run build Script
        working-directory: ./sdkclone
        run: |
           chmod +x xcode_build.sh
           sh xcode_build.sh
        shell: bash
        
      - name: Commit Framework File and update tag
        working-directory: ./
        run: |
          rm -rf ./inai_ios_sdk.xcframework
          mv ./sdkclone/inai_ios_sdk.xcframework ./inai_ios_sdk.xcframework
          
          git config --global user.email "support@inai.io"
          git config --global user.name "${{ secrets.GH_USERNAME }}"

          git remote set-url --push origin https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_TOKEN }}@github.com/inaitech/inai-pod.git

          VER=${GITHUB_REF#refs/*/}
          SVER="${VER//v}"
          
          git push --delete origin ${VER}
          
          git add inai_ios_sdk.xcframework
          git commit -m "Updating framework file to latest"

          git tag ${SVER}
          git push origin ${SVER}
          git push origin HEAD:main
        shell: bash
          
      # Install Cocoapods on the machine
      - name: Install Cocoapods
        run: gem install cocoapods
        
      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export POD_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
